<a href="https://colab.research.google.com/github/cristiandarioortegayubro/P4DA/blob/main/python_000.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![](https://github.com/cristiandarioortegayubro/P4DA/blob/main/Logo.png?raw=true)

![logo](https://www.python.org/static/community_logos/python-powered-h-70x91.png)

<p>
<font color="RoyalBlue">

**En este cuaderno comenzamos viendo los tipos de datos más simples de Python, los números, y también se desarrollaran operaciones matemáticas básicas, pero previo a ello, un breve contenido teórico de lo que es Python...**

</font>
</p>

## **<font color="RoyalBlue">Breve contenido teórico...</font>**

Python puede ser fácil de aprender, tanto para el programador que por primera vez incursiona en el lenguaje o tenga experiencia con otros lenguajes, como para el que no es programador. Las siguientes páginas son un primer paso útil para comenzar a escribir programas y scripts con Python:

*   [Guía para principiantes, no programadores](https://wiki.python.org/moin/BeginnersGuide/NonProgrammers)
*   [Muestra de código y fragmentos para principiantes](https://wiki.python.org/moin/BeginnersGuide/Examples)
*   [Documentación de Python](http://docs.python.org/)

### **<font color="RoyalBlue">Mini lecciones previas de Python</font>**

#### **<font color="RoyalBlue">Elementos de un script</font>**

Se podría decir que un script de Python contiene expresiones y sentencias. Esas expresiones y sentencias se consiguen combinando los elementos básicos del lenguaje.

El lenguaje Python está formado por elementos de diferentes tipos:

- *Palabras reservadas (keywords)*
- *Funciones integradas (built-in functions)*
- *Literales*
- *Operadores*
- *Delimitadores*
- *Identificadores*

##### **<font color="RoyalBlue">Palabras reservadas (keywords)</font>**

*Algunas de las palabras reservadas de Python son las que forman el núcleo del lenguaje Python, por ahora es importante conocer algunas de ellas, durante el transcurso del desarrollo de los notebooks, usaremos algunas de estas palabras reservadas:*

~~~python
False      await      else      import     pass
None       break      except    in         raise
True       class      finally   is         return
and        continue   for       lambda     try
as         def        from      nonlocal   while
assert     del        global    not        with
async      elif       if        or         yield
~~~


*Estas palabras no pueden utilizarse para nombrar otros elementos, es decir para crear variables...*

##### **<font color="RoyalBlue">Funciones integradas (built-in functions)</font>**

*Una función es un bloque de instrucciones agrupadas, que permiten reutilizar partes de un programa. Python incluye las siguientes funciones de forma predeterminada (estas funciones siempre están disponibles):*


~~~python
abs()         dict()      help()        min()        setattr()
all()         dir()       hex()         next()       slice()
any()         divmod()    id()          object()     sorted()
enumerate()   input()     oct()         bin()        eval()      
int()         open()      str()         bool()       exec()
isinstance()  ord()       sum()         bytearray()  filter()
issubclass()  pow()       super()       float()      iter()      
print()       tuple()     callable()    format()     len()       
property()    type()      chr()         frozenset()  list()
range()       vars()      classmethod() getattr()    locals()     
repr()        zip()       compile()     globals()    map()        
reversed()    complex()   hasattr()     max()        round()
delattr()     hash()      memoryview()  set()
~~~

##### **<font color="RoyalBlue">Literales</font>**

*Los literales son los datos simples que Python es capaz de manejar:*

- *números*: valores lógicos, enteros, decimales y complejos, en notación decimal, octal o hexadecimal
- *cadenas de texto*

##### **<font color="RoyalBlue">Operadores</font>**

*Los operadores son los caracteres que definen operaciones matemáticas (lógicas y aritméticas). Son los siguientes:*

~~~python
+       -       *       **      /       //      
<<      >>      &       |       ^       ~
<       >       <=      >=      ==      !=
%      @
~~~

##### **<font color="RoyalBlue">Delimitadores</font>**

*Los delimitadores son los caracteres que permiten delimitar, separar o representar expresiones. Son los siguientes:*

~~~python
'       "       #       \
(       )       [       ]       {       }
,       :       .       ;       @       =       ->
+=      -=      *=      /=      //=     %=      @=
&=      |=      ^=      >>=     <<=     **=
~~~

##### **<font color="RoyalBlue">Identificadores</font>**

*Los identificadores son las palabras que se utilizan para nombrar elementos creados por el usuario u otros usuarios. Esos elementos pueden ser variables u objetos que almacenan información, funciones que agrupan instrucciones, clases que combinan ambos, módulos que agrupan los elementos anteriores, etc.*

*Los identificadores están formados por letras (mayúsculas y minúsculas), números y el carácter guion bajo (_). Pueden ser caracteres Unicode, aunque normalmente se recomienda utilizar caracteres ASCII para evitar complicaciones a usuarios de otros países que utilizan juegos de caracteres diferentes.*

*El primer caracter del identificador debe ser una letra.*

## **<font color="RoyalBlue">Datos numéricos y cadenas de caracteres</font>**

### **<font color="RoyalBlue">Datos numéricos</font>**

#### <font color="RoyalBlue">**Enteros, decimales y números complejos**</font>

**Los números enteros para Python son aquellos que no contienen fracciones, es decir, sin decimales. Por otro lado, los números decimales usan como separador entre la parte entera y la parte decimal al punto. En el caso de números complejos, Python puede hacer cálculos con ellos. La parte imaginaria se acompaña con la letra ```j```.**

##### <font color="RoyalBlue">**Enteros**</font>

In [1]:
2023

2023

*2023 es un número entero.*

##### <font color="RoyalBlue">**Decimales**</font>

In [2]:
345.90

345.9

*345.90 es un número decimal, se recuerda que la parte decimal se indica con el punto, *no con la coma*. Es decir, cualquier número entero que se le adicione un punto, pasa a ser un número decimal.*

In [3]:
345.

345.0

##### <font color="RoyalBlue">**Complejos**</font>

In [4]:
34j

34j

*```34j``` es un número complejo. La letra ```j``` debe colocarse a continuación del número entero o decimal.*

In [5]:
387.9j

387.9j

##### **<font color="RoyalBlue">Positivos y negativos</font>**

**Se puede indicar si el número es positivo o es negativo.**

In [6]:
+583.97

583.97

*583.97 es un número positivo, en este caso no haría falta agregar el operador + al inicio del número. Por defecto los números son positivos.*

In [7]:
-785.52

-785.52

*-785.52 es un número negativo.*

### <font color="RoyalBlue">**Operaciones básicas**</font>

**Las cuatro operaciones básicas son:**

+ **la suma (+),**
+ **la resta (-),** 
+ **la multiplicación (*) y** 
+ **la división (/).**

*Al hacer operaciones en las que intervienen números enteros y decimales, el resultado es siempre decimal.* En el caso de que el resultado no tenga parte decimal, Python escribe 0 como parte decimal para indicar que el resultado es un número decimal

#### <font color="RoyalBlue">**Sumas y restas**</font>

**En este caso, las sumas y las restas funcionan como esperamos que funcionen.**

In [8]:
20+89+90+53

252

*No es necesario dejar espacios entre los números y el símbolo +, si existen espacios Python no los tiene en cuenta.*

In [9]:
20 + 89    +        90                +                     53

252

+ **Las operaciones de números enteros, dan por resultados números enteros.**
+ **Las operaciones de números decimales, dan por resultados números decimales.**
+ **Las operaciones de números complejos dan por resultados números complejos.**
+ **Las operaciones de números enteros y números decimales, dan por resultado números decimales.**
+ **Las operaciones de números complejos y números enteros y/o decimales, dan por resultado el número entero y/o decimal con el número complejo.**

In [10]:
800 + 300 + 200 - 800

500

In [11]:
30.70 + 20.10

50.8

In [12]:
2.5 + 2.5

5.0

**Si bien la operación 2.5 + 2.5 es una operación matemática que sabemos que da por resultado un número entero, al tratarse de dos números decimales, el resultado es un número decimal, en este caso indicado por el punto y el cero.**

In [13]:
20j + 30j

50j

In [14]:
20j + 30

(30+20j)

In [15]:
20j - 30

(-30+20j)

In [16]:
20j + 30.9

(30.9+20j)

In [17]:
10j + 15 -5j +20 

(35+5j)

#### <font color="RoyalBlue">**Multiplicaciones y divisiones**</font>

In [18]:
20 * 3

60

In [19]:
20 * 3.5

70.0

In [20]:
20 * 3j

60j

In [21]:
20j * 3

60j

**Ahora bien, en el caso de las divisiones de números enteros o números decimales, el resultado siempre será un número decimal. Cuando la operación sea de un número complejo, el resultado no será decimal, a menos que el número complejo tenga decimal.**

In [22]:
60 / 3

20.0

In [23]:
60.9 / 3

20.3

In [24]:
60j / 3

20j

In [25]:
60.9j / 3

20.3j

**También en el caso de las divisiones, se puede obtener como resultado solo la parte entera del número con dos símbolos /**

In [26]:
60 / 4

15.0

In [27]:
60 // 4

15

#### <font color="RoyalBlue">**Algunas cuestiones en las operaciones básicas**</font>

**Cuando en una operación matemática aparecen varias operaciones, Python resuelve con las reglas de prioridad de las operaciones matemáticas, es decir, primero las multiplicaciones y divisiones, y luego las sumas y las restas...**

In [28]:
8 + 8 / 2 + 2

14.0

**Si en la operación matemática se desea un orden específico, entonces debe ser indicado con el uso de paréntesis...**

In [29]:
(8 + 8) / (2 + 2)

4.0

**Al realizar operaciones con números decimales, los resultados pueden presentar errores de redondeo....**

In [30]:
100 / 3

33.333333333333336

**Este error se debe a que Python almacena los números decimales en binario con 53 bits de precisión (formato de coma flotante de doble precisión de la norma IEEE-754) y pasar de decimal a binario provoca errores de rendodeo. Si se necesita precisión absoluta, se deben utilizar módulos específicos para ello.**

**Debido a esos errores de redondeo, dos operaciones matemáticas que debieran arrojar el mismo resultado, podrían dar resultados levemente diferentes, pero diferentes.**

In [31]:
4 * 3 / 5

2.4

In [32]:
4 / 5 * 3

2.4000000000000004

### <font color="RoyalBlue">**Potencias y raices**</font>

**Las potencias se calculan con el operador $**$, teniendo en cuenta que $x$ $**$ $y$ $=$ $x^y$. Utilizando exponentes negativos o decimales se pueden calcular potencias inversas o raíces n-ésimas.**

**Si se quiere calcular un valor al cuadrado, por ejemplo $9^2$, entonces...**

In [33]:
9 ** 2

81

**O si se quiere calcular la raiz de un número, por ejemplo $\sqrt{9}$
entonces...**

In [34]:
9 ** 0.5

3.0

**La raíz de un número entero da como resultado un número decimal.**

In [35]:
81 ** 0.5

9.0

### <font color="RoyalBlue">**Bases**</font>

**Los números enteros son base 10 a menos que se utilice un prefijo para especificar otra base. Es posible que nunca necesitemos usar estas otras bases, pero nunca se sabe. Un ejemplo de ello son los números binarios (ceros y uno) que son base 2.**

**En Python, los números enteros se pueden expresar en tres bases:**

+ **base binaria (base 2)**
+ **base octal (base 8)**
+ **base hexadecimal (base 16)**

**Estas bases son todas potencias de dos, y son útiles en algunos casos.**

#### **Base 10**

In [36]:
10

10

#### **Base 2**

In [37]:
0b1010

10

#### **Base 8**

In [38]:
0o12

10

#### **Base 16**

In [39]:
0xa

10

#### <font color="RoyalBlue">**Funciones integradas para bases**</font>

**Para corroborar los valores equivalentes en las distintas bases, se pueden utilizar funciones integradas.**

In [40]:
10

10

In [41]:
bin(10)

'0b1010'

In [42]:
oct(10)

'0o12'

In [43]:
hex(10)

'0xa'

### <font color="RoyalBlue">**Usando algunas de las funciones integradas**</font>

#### **```int()```**

**Para cambiar un tipo de dato numérico a entero se utiliza la función ```int()```**

In [44]:
int(198.96)

198

In [45]:
int(1.0e4)

10000

**También con la función ```int()``` se puede convertir una cadena de caracteres en números... pero esa cadena de caracteres debería indicar un número entero, positivo o negativo.**

In [46]:
int("35")

35

In [47]:
int("-890")

-890

**Con la cadena de caracters no decimal, tambien se le puede indicar la base como segundo parámetro de la función ```int()```**

In [48]:
int("10", 10)

10

In [49]:
int("10", 2)

2

In [50]:
int("10", 8)

8

In [51]:
int("10", 16)

16

## <font color="RoyalBlue">**Cadenas de caracteres**</font>

**En principio las cadenas de caracteres se pueden delimitar con comillas simples o con comillas dobles...**

In [52]:
'Esta es una cadena de caracteres'

'Esta es una cadena de caracteres'

In [53]:
print('Esta es una cadena de caracteres')

Esta es una cadena de caracteres


In [54]:
print("Esta es una cadena de caracteres")

Esta es una cadena de caracteres


In [55]:
"2022"

'2022'

In [56]:
print("2022")

2022


**Como se puede observar, la función ```print()``` muestra por la pantalla de nuestro dispositivo el contenido de la cadena de caracteres, pero no muestra las comillas delimitadoras de la cadena.**

### <font color="RoyalBlue">**Concatenación**</font>

**Algo más que importante para destacar es que las cadenas de caracteres en Python son *inmutables*, y las cadenas de caracteres pueden concatenarse automáticamente.** 

In [57]:
"Py" "thon " "for " "Da" "ta " "Analy" "sis "

'Python for Data Analysis '

### <font color="RoyalBlue">**Subíndices**</font>

In [58]:
activo = "Activo"
pasivo = "Pasivo"
patrimonio = "Patrimonio Neto"

**Para obtener el primer caracter de alguna de las variables definidas, se indica ese caracter por su posición, entre corchetes, teniendo en cuenta que en Python siempre se empieza a contar desde cero. En el caso del Activo, si queremos la letra A, entonces debemos indicar el primer subíndice de la variable activo.**

In [59]:
activo[0]

'A'

In [60]:
print(activo[0])

A


### <font color="RoyalBlue">**Subcadenas**</font>

**Tambien se pueden obtener subcadenas de caracteres de las variables de texto.**

In [61]:
print(activo[0:3])

Act


In [62]:
print(pasivo[0:3])

Pas


In [63]:
print(patrimonio[0] + patrimonio[11:15])

PNeto


### <font color="RoyalBlue">**Uso de caracteres especiales**</font>

**Con el uso de los caracteres \n se puede adicionar una linea más de texto, escribiendo todo el script en una línea.**

In [64]:
print("Python for Data Analysis \nFirst Edition")

Python for Data Analysis 
First Edition


Con el uso de los caracteres ```\t``` se puede centrar la cadena de caracteres.

In [65]:
print("\tPython for Data Analysis \n\tFirst Edition")

	Python for Data Analysis 
	First Edition


### <font color="RoyalBlue">**Usando algunas de las funciones integradas**</font>

#### **```str()```**

**Se puede crear una cadena de caracteres a partir de otro tipo de datos mediante la función str()**

In [66]:
str(987.90)

'987.9'

In [67]:
str(True)

'True'

#### **```len()```**

**Esta función cuenta cuantos caracteres hay en una cadena de caracteres.**

In [68]:
len("Python for Data Analysis")

24

#### **```capitalize()```**

**Se aplica sobre una cadena de caracteres y devuelve la primera letra en mayúscula...**

In [69]:
texto = "python for data analysis"

In [70]:
texto.capitalize()

'Python for data analysis'

In [71]:
texto = texto.capitalize()

#### **```lower()```**

**Convierte todos los caracteres en minúscula...**

In [72]:
texto

'Python for data analysis'

In [73]:
texto.lower()

'python for data analysis'

In [74]:
texto = texto.lower()

#### **```upper()```**

**Convierte todos los caracteres en mayuscula...**

In [75]:
texto

'python for data analysis'

In [76]:
texto.upper()

'PYTHON FOR DATA ANALYSIS'

In [77]:
texto = texto.upper()

#### **```split()```**

**Divide una cadena de caracteres en subcadenas dentro de una lista. La división se realiza en virtud de lo que se indica en un parámetro**


In [78]:
texto

'PYTHON FOR DATA ANALYSIS'

In [79]:
texto.split(sep=" ")

['PYTHON', 'FOR', 'DATA', 'ANALYSIS']

#### **```replace()```**

**Este metodo recibe dos parámetros, el primero es la cadena a reemplazar, y el segundo la cadena nueva que lo va a reemplazar**

In [80]:
texto

'PYTHON FOR DATA ANALYSIS'

In [81]:
texto.replace("ANALYSIS","SCIENCE")

'PYTHON FOR DATA SCIENCE'

---
<p>
<font color="RoyalBlue">

💙 **Hemos llegado al fin de este cuaderno, felicitaciones hemos aprendido operaciones básicas numéricas, cadenas de caracteres y hemos usado algunas funciones integradas de Python, ahora a seguir en el proximo cuaderno...** 
</font>
</p>

---

# 😀

![](https://everisgroup.sharepoint.com/sites/BrandCenter/Shared%20Documents/Logo/FUTURE%20AT%20HEART/BLACK/FUTURE-HEARTH.png)